name: Build and Release

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.spec.js"
      - ".idea/**"
      - ".vscode/**"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_on_${{ matrix.os }}
          path: release/
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/
      - name: List Files in Release Directory
        run: ls -R release/
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.1.1
          name: "Release v0.1.1"
          draft: false
          prerelease: false
          artifacts: |
            release/**/**/*.exe
            release/**/**/*.dmg
            release/**/**/*.AppImage
          token: ${{ secrets.GHP_TOKEN }}
